### ISSUE TITLE
Allow choice of LLVM version for source builds

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGPU/gitlab-ci#14]
For the AMDGPU stack, it would be really helpful to have a few extra CI runs on Julia with LLVM 7 and 8 (and eventually future versions of LLVM).

**Comment by maleadt** [comment]
Since I'm moving away from prebuilt Docker images, it would be best to build that yourself (or better, have BinaryBuilder provide packages). Here's an example: https://github.com/maleadt/LLVM.jl/blob/792edc1fe9471b95bad87c619d25c87befe92a60/.gitlab-ci.yml#L37-L49

**Comment by jpsamaroo** [comment]
So I finally got around to working on this, and am now trying to get source builds working on AMDGPUnative.jl [1]. However, I'm running into build errors related to mismatching SHA512 sums [2]. Would you have any insight into why these are occuring?

[1] https://github.com/JuliaGPU/AMDGPUnative.jl/pull/21/files
[2] https://gitlab.com/JuliaGPU/AMDGPUnative.jl/-/jobs/379797043

**Comment by maleadt** [comment]
Probably https://github.com/JuliaLang/julia/pull/34108. I've restarted the build: https://gitlab.com/JuliaGPU/AMDGPUnative.jl/-/jobs/380060552

**Comment by maleadt** [comment]
Seems to work now (the build fails for unrelated reasons).
