### ISSUE TITLE
Julia 1.3

### ISSUE THREAD

**Issue by navidcy** [JuliaGPU/gitlab-ci#17]
Is it time to move to the official v1.3?
https://github.com/JuliaGPU/gitlab-ci/blob/8b7b03c9d1e16a314f790b9f072dcea418e7b5b1/images/base/v1.3/Dockerfile#L14

**Comment by maleadt** [comment]
So the reason this hasn't been adjusted is that I'm mostly on the v6 template now, which doesn't rely on Docker images (which I plan to deprecate in the future) but downloads Julia instead: https://github.com/JuliaGPU/gitlab-ci/blob/8b7b03c9d1e16a314f790b9f072dcea418e7b5b1/templates/v6.yml#L105

Is there any reason you're using an older template that relies on the Docker images?

**Comment by navidcy** [comment]
OK, I just got confused then. I am using v6 but I thought this was referring to what v6 was using.

I've been bugging my head on the wall to figure out why FourierFlows.jl stalls using Julia v1.3 (see https://github.com/FourierFlows/FourierFlows.jl/issues/139)...

**Comment by maleadt** [comment]
Yeah, the versioninfo in that log shows 1.3.1, so that doesn't seem to be the issue...
